# Spring properties
spring:
  application:
    name: stats-collector

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 2001   # HTTP (Tomcat) port